# Generated by Django 5.0 on 2023-12-05 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_rename_descrition_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billproduct',
            old_name='pruduct',
            new_name='product',
        ),
    ]
