# Generated by Django 5.0 on 2023-12-05 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_rename_pruduct_billproduct_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='client',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='billproduct',
            old_name='bill',
            new_name='bill_id',
        ),
        migrations.RenameField(
            model_name='billproduct',
            old_name='product',
            new_name='product_id',
        ),
    ]
